### ISSUE TITLE
Support for nested lists? 

### ISSUE THREAD

**Issue by jacoblippincott** [danomatic/react-pdf-html#30] opened 2022-05-11 18:58 UTC
Does this package support nested lists? I have a <ul> nested inside a <ol> and in the rendered PDF I see that the bullet points are positioned in front of the unordered list items as expected but they are all on a single line. I can provide code and output if you would like.

**Comment by danomatic** [comment] 2022-05-12 21:08
I don't think nested lists have been tested yet, but that shouldn't be very hard to solve. PRs welcome :-)

There may be a way to do a temporary fix for this with a stylesheet.

**Comment by TimHav** [comment] 2022-06-23 09:58
As a temporary fix you can add some `padding-left` to the nested list. For example:

```html
<ul>
  <li>...</li>
  <ul style="padding-left: 30pt">
    <li>...</li>
    <li>...</li>
  </ul>
</ul>
```

**Comment by zbiggs1** [comment] 2022-10-05 19:59
I'm also having the same issue. Puts the nested list's items inline. I can't seem to get CSS to jerryrig it either.

**Comment by danomatic** [comment] 2022-10-10 22:24
@jacoblippincott this should be fixed in the latest version `v1.1.13`. It was caused by rendering list item content as inline/text

**Closed by danomatic** 2022-10-10 22:24 UTC
Labels: bug, help wanted
